import express from 'express';
import cors from 'cors';
import path from 'path';
import authRoutes from './routes/authRoutes';
import documentRoutes from './routes/documentRoutes';
import dashboardRoutes from './routes/dashboardRoutes';
import webhookRoutes from './routes/webhookRoutes';
import fileRoutes from './routes/fileRoutes';
import generateRoutes from './routes/generateRoutes';
import userRoutes from './routes/userRoutes';
import configRoutes from './routes/configRoutes';
import notificationRoutes from './routes/notificationRoutes';
import asignacionRoutes from './routes/asignacionRoutes';

const app = express();

// CORS: permite la URL del frontend configurada (producción) y cualquier puerto
// de localhost en desarrollo (Vite puede arrancar en 5173, 5174, …).
const allowedOrigins = [process.env.FRONTEND_URL].filter(Boolean) as string[];
app.use(
  cors({
    origin: (origin, cb) => {
      const ok =
        !origin ||
        allowedOrigins.includes(origin) ||
        /^https?:\/\/localhost:\d+$/.test(origin);
      cb(null, ok);
    },
    credentials: true,
  })
);

app.use(express.json({ limit: '10mb' }));
app.use(express.urlencoded({ extended: true }));

// Serve uploaded documents (PDFs, HTMLs generated by n8n)
app.use('/uploads', express.static(path.join(process.cwd(), 'uploads')));

// Serve the demands/anexos stored on the office NAS (mounted folder) so the web
// can show the already-generated documents. DOCS_DIR = ruta de la carpeta de la
// NAS (o el montaje cifs). Si no se define, esta ruta queda inactiva.
if (process.env.DOCS_DIR) {
  app.use('/docs', express.static(process.env.DOCS_DIR));
}

app.use('/api/auth', authRoutes);
app.use('/api/documents', documentRoutes);
app.use('/api/dashboard', dashboardRoutes);
app.use('/api/webhook', webhookRoutes);
app.use('/api/files', fileRoutes);
app.use('/api/generate', generateRoutes);
app.use('/api/users', userRoutes);
app.use('/api/config', configRoutes);
app.use('/api/notifications', notificationRoutes);
app.use('/api/asignaciones', asignacionRoutes);

app.get('/health', (_req, res) => {
  res.json({ status: 'ok', timestamp: new Date().toISOString() });
});

export default app;
